name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dev-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run startup script
        run: |
          python src/hello.py