name: Executar MLP Iris

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-mlp:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar main.py
      run: |
        python main.py | tee saida_execucao.txt

    - name: Upload do relatório final
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-final
        path: |
          relatorio_final.txt
          saida_execucao.txt
